app = "neo-analytics-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  KAFKAJS_NO_PARTITIONER_WARNING = "1"

[[services]]
  internal_port = 3001
  protocol = "tcp"
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]
  
  [[services.ports]]
    port = 3001
    handlers = ["http"]

[mounts]
  source = "kafka_data"
  destination = "/var/lib/kafka/data"

# Keep memory usage low
[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1